### PR TITLE
Fix node version by using `nvm` and read project node version from `.nvmrc` file (K-1811)

### PR DESCRIPTION
**Pull request by plutonik-a**
This PR introduces breaking changes:
1. You need to have `nvm` installed.
2. You need to install node v17.6.0 via nvm with this command: `nvm install v17.6.0`. Once you have installed it, the project's `.nvmrc` file file will switch back to this version even if you have another node version running on your system.
3. You need to have Chrome >=110 installed because of the latest chromedriver version. If you need a lower version, please edit it your version for chromedriver version (aka Chrome version) in `package.json` and refer to the readme for troubleshooting.
4. Run `npm install` before running ant once to check, if everything has been updated. In case of trouble with package-lock.json, just delete it and run npm install again. 

---

Base branch of this PR is an old and open PR https://github.com/HistoryAtState/hsg-shell/pull/387.
(See comments and feature list there.)

The added features of this contribution are:
* Update node version to v17.6.0.
* Run ant in one command: 
    * Set local build properties by retrieving the value of environment variable `$NVM_BIN`, which is set when installing `nvm` (https://github.com/nvm-sh/nvm/blob/master/README.md#environment-variables).
    * Copy value of `$NVM_BIN` to the local build properties and concatenate with according application binary, as gulp and npm will be installed in following path pattern:`<user.home>/.nvm/versions/node/<version>/bin/<binary>
    * Add dependencies chain from default target > `run-npm`> `node` > `prepare` to be able to build the xar file plus edit the local settings in one command.
* Updated Readme. 

Note: There is another open and related PR by Adam, which should be incorporated into this one, too: https://github.com/HistoryAtState/hsg-shell/pull/388

### CODE REVIEW

**Review by yamahito — APPROVED** [review]
I couldn't quite believe how quickly it built - nice one.

**Comment by joewiz** [comment]
According to https://github.com/nvm-sh/nvm/blob/master/README.md#nvmrc:

> The contents of a `.nvmrc` file must be the `<version>` (as described by `nvm --help`) followed by a newline. No trailing spaces are allowed, and the trailing newline is required.

I see that https://github.com/evolvedbinary/hsg-shell/pull/33/commits/7d82a0f333e573fdd9118ad5c071182a9f70edce removed the trailing newline from the `.nvmrc` file. 

A solution for reading just the 1st line of a file via loadfile is here: https://stackoverflow.com/questions/40593933/how-to-read-just-a-first-line-of-an-file-txt-with-ant.

**Comment by joewiz** [comment]
I've finished my review of this PR in its current state. The only issue I found is listed above.

**Comment by plutonik-a** [comment]
> According to https://github.com/nvm-sh/nvm/blob/master/README.md#nvmrc:
> > The contents of a `.nvmrc` file must be the `<version>` (as described by `nvm --help`) followed by a newline. No trailing spaces are allowed, and the trailing newline is required.
> I see that [7d82a0f](https://github.com/evolvedbinary/hsg-shell/commit/7d82a0f333e573fdd9118ad5c071182a9f70edce) removed the trailing newline from the `.nvmrc` file.
> A solution for reading just the 1st line of a file via loadfile is here: https://stackoverflow.com/questions/40593933/how-to-read-just-a-first-line-of-an-file-txt-with-ant.

Thank you @joewiz for spotting this!

The above solution for filtering the first line of the `nvmrc` file doesn't solve the problem, as we don't want the newline character to be copied - that would insert a new line into our binary path. Therefore I have used a similar task to filter out specifically the new line of the file (f890d16fba59c6a419b642493c112f9c2d1a9fa7):

```xml
<loadfile property="nvm_version" srcFile=".nvmrc">
  <filterchain>
      <filterreader classname="org.apache.tools.ant.filters.StripLineBreaks"/>
  </filterchain>
</loadfile>
```

**Review by joewiz — APPROVED** [review]
Great! Thank you!

**Pull request merged**
